name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t mcappy/react-test -f ./client/Dockerfile.dev ./client
    - name: Run the tests
      run: docker run -e CI=true mcappy/react-test npm test -- --coverage

  Deploy:
    
    runs-on: ubuntu-latest
    needs: Test
    
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker
    - run: docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Building Production Images
    - run: docker build -t mcappy/multi-client ./client
    - run: docker build -t mcappy/multi-nginx ./nginx
    - run: docker build -t mcappy/multi-server ./server
    - run: docker build -t mcappy/multi-worker ./worker
    
    - name: Push to Docker Hub
    - run: docker push mcappy/multi-client
    - run: docker push mcappy/multi-nginx
    - run: docker push mcappy/multi-server
    - run: docker push mcappy/multi-worker
        
      
      
