name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t mcappy/react-test -f ./client/Dockerfile.dev ./client
    - name: Run the tests
      run: docker run -e CI=true mcappy/react-test npm test -- --coverage

  Deploy:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Building Production Images
      run: | 
        docker build -t mcappy/multi-client ./client
        docker build -t mcappy/multi-nginx ./nginx
        docker build -t mcappy/multi-server ./server
        docker build -t mcappy/multi-worker ./worker
    - name: Login to Docker Hub
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to Docker Hub
      run: |
        docker push mcappy/multi-client
        docker push mcappy/multi-nginx
        docker push mcappy/multi-server
        docker push mcappy/multi-worker
        
      
      
