name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t mcappy/react-test -f ./client/Dockerfile.dev ./client
    - name: Run the tests
      run: docker run -e CI=true mcappy/react-test npm test -- --coverage

  Deploy:
    
    runs-on: ubuntu-latest
    needs: Test
    
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Images
        run: |
          docker build -t mikecappeller/multi-client ./client
          docker build -t mikecappeller/multi-nginx ./nginx
          docker build -t mikecappeller/multi-server ./server
          docker build -t mikecappeller/multi-worker ./worker

      - name: Push to Docker Hub
        run: |
          docker push mikecappeller/multi-client
          docker push mikecappeller/multi-nginx
          docker push mikecappeller/multi-server
          docker push mikecappeller/multi-worker
      
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      
      - name: Deploy to to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multidocker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-015373660542
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
          
        
      
      
